services:
  expenses-service:
    container_name: expenses-service
    build:
      context: build/local
    volumes:
      - .:/expenses
    working_dir: /expenses
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: